# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 219ec456e254dd0664a533a06e5b3dc157e5e20efecf73590b25c67ec912b26c2218838720c35724c89cc7af1c9d605243228d32ac76654d5196cef62f52ec44

test:
  secret_key_base: 51c2b89bdde2057fc635de88168cb0a8bcb09108d9893d3951939bfe2db3ee841a7d3bafd667b9129ba78b2433d0d7918a51216941b504d2bd61d2efbfe78422

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
